language: php
php:
  - 5.4
  - 5.5
env:
  - DB:sqlite
before_script: composer install --dev --prefer-source --no-interaction
script: phpunit --coverage-clover build/logs/clover.xml
after_script: ./vendor/bin/coveralls -v
